// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package entites

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string
	Userid                string
	Accountid             string
	Providerid            string
	Accesstoken           pgtype.Text
	Refreshtoken          pgtype.Text
	Accesstokenexpiresat  pgtype.Timestamptz
	Refreshtokenexpiresat pgtype.Timestamptz
	Scope                 pgtype.Text
	Idtoken               pgtype.Text
	Password              pgtype.Text
	Createdat             pgtype.Timestamptz
	Updatedat             pgtype.Timestamptz
}

type Session struct {
	ID        string
	Userid    string
	Token     string
	Expiresat pgtype.Timestamptz
	Ipaddress pgtype.Text
	Useragent pgtype.Text
	Createdat pgtype.Timestamptz
	Updatedat pgtype.Timestamptz
}

type User struct {
	ID            string
	Name          pgtype.Text
	Email         pgtype.Text
	Emailverified bool
	Image         pgtype.Text
	Createdat     pgtype.Timestamptz
	Updatedat     pgtype.Timestamptz
}

type Verification struct {
	ID         string
	Identifier string
	Value      string
	Expiresat  pgtype.Timestamptz
	Createdat  pgtype.Timestamptz
	Updatedat  pgtype.Timestamptz
}
